[tool.poetry]
name = "pypme"
version = "0.1.1"
description = "Python library for PME (Public Market Equivalent) calculation"
authors = ["ymyke"]
license = "MIT"
repository = "https://github.com/ymyke/pypme"
homepage = "https://github.com/ymyke/pypme"

[tool.poetry.dependencies]
python = ">=3.8, <3.10"
xirr = "^0.1.8"
numpy-financial = "^1.0.0"
pandas = "^1.4.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipykernel = "^6.9.1"
black = "^22.1.0"
hypothesis = "^6.39.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
